Test speaker shellcheck fixes
thesofproject/sof-test pull request #1047
Opened 2023-05-31 23:24 UTC by greg-intel

Fixed a variety of quoting issues.

[Rewrite and reverse error conditions.](https://github.com/thesofproject/sof-test/commit/c10f5e9fef7461a8c1f32878809dea62a5eb53cb)

Signed off by Greg Galloway greg.galloway@intel.com

2023-05-31 23:30 UTC, marc-hb requested changes
Looks good except for the 2nd error message which is basically... missing. This is a bug fix! So it must mention the test name in the title and a short description of the bug, something like: "now checking exit status of speaker-test command.

2023-05-31 23:30 UTC, marc-hb commented on test-case/test-speaker.sh
> +	[[ $resultRet -ne 0  ]]; then
nit: indent this line

2023-06-01 19:41 UTC, greg-intel commented on test-case/test-speaker.sh
> +	[[ $resultRet -ne 0  ]]; then
Fixed.

2023-06-01 19:42 UTC, greg-intel commented
> Looks good except for the 2nd error message which is basically... missing. This is a bug fix! So it must mention the test name in the title and a short description of the bug, something like: "now checking exit status of speaker-test command"

The commit message?  Updated.

2023-06-02 21:40 UTC, merged