Shellcheck check suspend resume with audio
thesofproject/sof-test pull request #1055
Opened 2023-06-12 22:29 UTC by greg-intel

Various shellcheck fixes, including quoting, source references and pgrep.

Work done under ticket https://github.com/thesofproject/sof-test/issues/729

Signed-off-by: Greg Galloway <greg.galloway@intel.com>

2023-06-12 23:12 UTC, marc-hb requested changes
> Rewrote conditional of a sof-process-state.sh line (that was basically broken).

It's not obvious why and how it was broken; please explain in the commit message the bug and also update the commit title. When people read "shellcheck fixes" they assume barely any functional change and no bug fix.

Some projects even require an actual bug to be filed before submitting a fix but we're not that pedantic here :-)

2023-06-12 23:12 UTC, marc-hb commented on test-case/check-suspend-resume-with-audio.sh
> +    "$(dirname "${BASH_SOURCE[0]}")"/check-suspend-resume.sh "${opt_arr[@]}"  || die "suspend resume failed"
Please de-duplicate `$(dirname "${BASH_SOURCE[0]})` with some new MYDIR variable like other scripts do.

2023-06-12 23:12 UTC, marc-hb commented on test-case/check-suspend-resume-with-audio.sh
> +    opt_arr+=("-S" "${OPT_VAL['S']}" "-w" "${OPT_VAL['w']}")
Surely shellcheck didn't ask you to quote `-S` and `-w`, did it?

2023-06-12 23:12 UTC, marc-hb commented on test-case/check-suspend-resume-with-audio.sh
> +    opt_arr+=("-r")
same as above
```suggestion
    opt_arr+=(-r)
```

2023-06-12 23:12 UTC, marc-hb commented on test-case/check-suspend-resume-with-audio.sh
> +opt_arr=("-l" "${OPT_VAL['l']}")
```suggestion
opt_arr=(-l "${OPT_VAL['l']}")
```

2023-06-12 23:12 UTC, marc-hb commented on test-case/check-suspend-resume-with-audio.sh
> +    opt_arr+=("-T" "${OPT_VAL['T']}")
same

2023-06-13 22:57 UTC, greg-intel commented on test-case/check-suspend-resume-with-audio.sh
> +    "$(dirname "${BASH_SOURCE[0]}")"/check-suspend-resume.sh "${opt_arr[@]}"  || die "suspend resume failed"
Done.

2023-06-14 00:55 UTC, marc-hb commented
https://github.com/thesofproject/sof-test/pull/1055/commits/32c98bb8a2c56c removes quotes that are added by an earlier commit. Don't add them in the first place.

2023-06-14 19:44 UTC, marc-hb commented
> There are many online examples that quote each element of arrays. Err'ing on the side of more quotes rather than less didn't seem like a serious problem.

This is a debatable code style question, I agree it can be subjective.

In any case:
- Never fix code that was just changed in a previous commit in the same PR. Do it right in the first and only commit.
- Don't do pure quoting fixes in lines that shellcheck had nothing to say about; I mean not in a "shellcheck" pull request.

2023-06-22 18:03 UTC, greg-intel commented
@marc-hb are there further opens on this PR?  I believe I've satisfied all the requests.

2023-06-22 20:34 UTC, greg-intel commented
SOFCI TEST

2023-06-23 20:05 UTC, greg-intel commented
All tests pass:
https://sof-ci.01.org/softestpr/PR1055/build482/devicetest/index.html
https://sof-ci.01.org/softestpr/PR1055/build483/devicetest/index.html
https://sof-ci.01.org/softestpr/PR1055/build484/devicetest/index.html

2023-06-26 20:34 UTC, marc-hb approved these changes

2023-06-28 07:35 UTC, merged