sof-kernel-log-check: ignore i915 firmware loading error
thesofproject/sof-test pull request #1104
Opened 2023-09-11 19:06 UTC by fredoh9

Filter out below errors:
[ 8196.630952] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: GuC initialization failed -ENXIO [ 8196.630953] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Enabling uc failed (-5) [ 8196.630955] kernel: i915 0000:00:02.0: [drm] *ERROR* GT0: Failed to initialize GPU, declaring it wedged!

Link: https://github.com/thesofproject/linux/issues/4530

2023-10-18 19:23 UTC, fredoh9 commented
@marc-hb @kv2019i I think this is very low risk PR. Any comment?

2023-10-18 19:29 UTC, marc-hb commented
"declaring GPU wedged!" does not sound like "low risk". It sounds more like a hard crash. If a GPU does not work then we should disable it and not try to use it, not try and let it crash.

2023-10-19 19:35 UTC, kv2019i commented
@marc-hb wrote:
> "declaring GPU wedged!" does not sound like "low risk". It 
> sounds more like a hard crash. If a GPU does not work then we should 
> disable it and not try to use it, not try and let it crash and corrupt kernel data 

While the error message is quit scary, I think the wedged state is fairly well defined and the driver is expected to continue to provide other services (it would panic otherwise). Given we don't really depend on the GPU parts, I think we can ignore this on specific DUTs.

2023-10-19 19:36 UTC, kv2019i submitted a review, later dismissed

2023-10-26 00:05 UTC, marc-hb requested changes
Please move this to the `adl|adl-s)` section below. It already has similar rules.

2023-11-02 02:43 UTC, keqiaozhang commented
SOFCI TEST

2023-11-02 16:12 UTC, marc-hb commented
@keqiaozhang your last SOFCI TEST did not work, the page still points at 2023-09-11 results:
https://sof-ci.01.org/softestpr/PR1104/build719/devicetest/index.html
https://sof-ci.01.org/softestpr/PR1104/build721/devicetest/index.html
https://sof-ci.01.org/softestpr/PR1104/build720/devicetest/index.html

This is probably related to more recent #1123 and others not having any jenkins results at all.

2023-11-28 19:09 UTC, fredoh9 commented
SOFCI TEST

2023-11-29 01:05 UTC, marc-hb approved these changes

2023-12-01 09:23 UTC, keqiaozhang commented
SOFCI TEST

2023-12-01 18:18 UTC, merged