sof_perf_analyzer: fix exception when kernel message not provided
thesofproject/sof-test pull request #1113
Opened 2023-10-11 09:14 UTC by aiChaoSONG

If kernel message file is not provided, the component_name dict will be empty, in calculating the maximum length of component names, we calls the max function with an empty sequence, which raises below error:
    "ValueError: max() arg is an empty sequence"

This patch checks if component_name dict is empty, and on empty, provides a default value.

2023-10-11 16:42 UTC, marc-hb requested changes

2023-10-11 16:42 UTC, marc-hb commented on tools/sof_perf_analyzer.py
> +        if component_name:
```suggestion
        if args.kmsg:
```
Either the user provided kmsg and then it must be correct. Or they didn't and we don't have component names.

We don't want to silently ignore bad kmsg arguments.

This also saves an explanation why `component_name` can be empty.

2023-10-13 01:25 UTC, btian1 approved these changes

2023-10-13 18:30 UTC, marc-hb commented
SOFCI TEST

2023-10-13 19:59 UTC, merged