test-socwatch.sh: no need to load socwatch module manually
thesofproject/sof-test pull request #1157
Opened 2024-01-31 04:50 UTC by keqiaozhang

We only use socwatch tool to read the power data for power measurement in this case, we can directly use the latest released version, so there is no need to pre-compile the driver.

2024-01-31 18:48 UTC, marc-hb requested changes
Please don't delete all the corresponding code. We are barely getting started in this area which means things will change in the future and we may need this again soon.

In fact it should be very easy to make the module loading and unload optional with just this:

```diff
- sudo "$SOCWATCH_PATH"/drivers/insmod-socwatch -q
+ sudo "$SOCWATCH_PATH"/drivers/insmod-socwatch -q || true
```

```diff
- check_socwatch_module_loaded || die "socwatch module not loaded"
+ check_socwatch_module_loaded || dlogi "socwatch module not loaded"
```

2024-02-01 05:27 UTC, marc-hb approved these changes
I don't find the commit message very accurate but... good enough.

We do need to load the driver manually; this PR just makes that optional.

2024-02-01 05:27 UTC, marc-hb commented on test-case/test-socwatch.sh
> +    dlogi "SoCWatch version: ${SOCWATCH_VERSION}"
I think you could have just run the command here but no big deal.

2024-02-01 07:32 UTC, keqiaozhang commented
Test report: https://sof-ci.ostc.intel.com/#/result/planresultdetail/37633

2024-02-01 18:03 UTC, marc-hb approved these changes

2024-03-15 16:09 UTC, marc-hb commented
@fredoh9 can we merge this?

2024-04-10 17:49 UTC, fredoh9 approved these changes
Looks good.

2024-04-10 17:52 UTC, merged