sof_remove: unload `snd_sof_intel_hda_common` before `soundwire_intel`
thesofproject/sof-test pull request #1182
Opened 2024-04-25 22:39 UTC by marc-hb

Fixes this failure with older kernel like the 6.5 kernels distributed by Ubuntu:

 ERROR: Module soundwire_intel is in use by: snd_sof_intel_hda_common

Fixes commit 65951c4d0 ("kmod: fix hda-sdw-bpt dependency") which unloaded all soundwire drivers earlier as a block. This is not a problem with 6.9-ish kernels where snd_sof_intel_hda_common and soundwire_intel can apparently be unloaded in any order but it is a problem with older kernels.

So, unload `snd_sof_intel_hda_common` before soundwire modules to be compatible with any kernel.

See https://github.com/thesofproject/sof-test/pull/1156 for more info.

2024-04-26 00:32 UTC, marc-hb commented
Known ALSABAT failure in https://sof-ci.01.org/softestpr/PR1182/build356/devicetest/index.html

Everything else green.

2024-04-29 18:50 UTC, plbossart requested changes

2024-04-29 18:50 UTC, plbossart commented on tools/kmod/sof_remove.sh
> +remove_module snd_sof_intel_hda_common
I am pretty sure this does not work if you have snd_sof_intel_hda_sdw_bpt in use.

See https://github.com/thesofproject/linux/pull/4679/commits/af779a3ca9bae844fb1691caaba7243e49afbe71#diff-117faa254cc1264b915358fff9c601a8b15e7545c3, the BPT stuff depends on the hda_common stuff.

so if you want to deal with older kernels, you can add this line and ignore errors, and keep it line 136 where it was.

2024-04-30 22:08 UTC, plbossart approved these changes

2024-05-01 00:16 UTC, marc-hb commented
Pretty bad looking but isolated and unrelated crash of `ba-lnlm-rvp-sdw-01`  in https://sof-ci.01.org/softestpr/PR1182/build370/devicetest/index.html?model=LNLM_SDW_AIOC&testcase=multiple-pause-resume-50

Everything else 100% green.

2024-05-01 00:16 UTC, merged