Updated check-sof-logger.sh and verify-kernel-boot-log.sh
thesofproject/sof-test pull request #1245
Opened 2024-12-17 18:43 UTC by harajend

Updated SOF-specific codecs since the sof* regex also lists sofprobes.

2024-12-17 19:36 UTC, marc-hb requested changes
- Are there any other possibilities besides these two? @kv2019i , @ranj063 , @bardliao can you answer?

- The commit message must link to the corresponding, e.g. "Fixes issue #1243 

- The commit title and message must describe the change much precisely. For instance: `check-sof-logger: remove wildcard from sof_alsa_card_found()`

See commit message examples in the git log.

Here are some good references, most of it apply to any open-source project so please take some time and take a look

https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-guidelines

https://wiki.openstack.org/wiki/GitCommitMessages

https://www.qemu.org/docs/master/devel/submitting-a-patch.html#write-a-meaningful-commit-message

https://www.kernel.org/doc/html/latest/process/submitting-patches.html#describe-your-changes

2024-12-17 19:36 UTC, marc-hb commented on test-case/check-sof-logger.sh
> +        test -e /proc/asound/sofhdadsp/id
The comment above does not make any sense after this change and must be removed (as shown in https://github.com/thesofproject/sof-test/issues/1243#issuecomment-2549132322)

2024-12-18 16:45 UTC, marc-hb commented
Simpler and probably good enough:

```sh
sof_alsa_card_found()
{
   for i in /proc/asound/sof*/id; do
      if test -e "$i"; then return 0; fi
   done
   return 1
}
```

2025-01-02 16:31 UTC, marc-hb commented
You need to use `git rebase -i` and squash the 2 git commits into a single one. We don't want to keep trial-and-error in the history; every git commit must work. Neither Zephyr nor SOF use Github in the "usual" way, they use it in the "traditional git" way https://github.com/zephyrproject-rtos/zephyr/issues/39194

Also, see advice above for a useful commit message.

2025-01-02 16:44 UTC, marc-hb commented
Jenkins did not test this at all :-(

2025-01-06 23:34 UTC, marc-hb commented
> Jenkins did not test this at all :-(

Still not running :-(

2025-01-07 20:34 UTC, marc-hb commented
Jenkins still not running; pushing new versions does not make any difference. Something is wrong on the Jenkins side. cc: @kv2019i

2025-01-09 22:01 UTC, marc-hb commented
There is still no testing.

Squashing looks good but the commit message of https://github.com/thesofproject/sof-test/pull/1245/commits/212a42023c04e3e0b92ca9c40a7204e74682b161  is still a mess:

```
Updated the test script with suggested changes

Signed-off-by: harajend <hariprasad.rajendra@intel.com>

Updated check-sof-logger.sh

Updated SOF-specific codecs since the sof* regex also lists sofprobes.

Signed-off-by: harajend <hariprasad.rajendra@intel.com>
```

Don't say "update", every commit is an update. Just describe the change (once).

2025-01-10 09:40 UTC, kv2019i requested changes
Mostly good, but some comments inline.

2025-01-10 09:40 UTC, kv2019i commented on test-case/verify-kernel-boot-log.sh
> +     amixer -c "$switch" cget name='Dmic0 Capture Switch'
Hmm, doesn't this still select a fixed card? 

E.g.
```
~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

... you'd get the same with "amixer -c 0" gets us.

2025-01-10 09:40 UTC, kv2019i commented on test-case/check-sof-logger.sh
>      # note: assumes SOF card names to start with "sof", e.g.
Change is good, but the commit message seems wrong. There are two signed offs. Can you amend the message and repush?

2025-01-11 01:26 UTC, marc-hb commented on test-case/verify-kernel-boot-log.sh
> +     amixer -c "$switch" cget name='Dmic0 Capture Switch'
`awk` is a "big boy" and can select lines itself. It's shorter AND more readable:

```shell
   switch=$(aplay -l |  awk 'NR == 2 {print $3}')
```

Of course `amixer -c 0` looks even better.

2025-01-11 01:45 UTC, marc-hb commented
test this please

2025-01-11 17:21 UTC, marc-hb commented
Jenkins is still not running :-( @harajend please try closing this one and re-submitting in a new PR?

2025-01-13 04:17 UTC, harajend commented on test-case/verify-kernel-boot-log.sh
> +     amixer -c "$switch" cget name='Dmic0 Capture Switch'
> @harajend But "head -2 | tail -1" will always pick the first card, so this is same as passing "amixer -c 0", right?

Yes, On functionality front both are same. Here I thought to pass "name/identifier" instead of "index number"

2025-01-13 06:29 UTC, harajend commented
Submitted new PR's for sof-logger and kernel-boot-log failures. Hence closing this (https://github.com/thesofproject/sof-test/pull/1245) pull request.
Sof-logger: https://github.com/thesofproject/sof-test/pull/1248
Kernel-boot-log: https://github.com/thesofproject/sof-test/pull/1249

2025-01-13 06:29 UTC, closed without merging