sof-kernel-log-check: fix last_line / begin_line off-by-one error
thesofproject/sof-test pull request #366
Opened 2020-09-08 23:30 UTC by marc-hb

If the last line of kern.log was an error then the _next_ test was failing.

Found thanks to the new fake_kern_error() function submitted separately.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2020-09-08 23:39 UTC, marc-hb commented
All the shellcheck warnings were already there, this adds none.

2020-09-09 00:55 UTC, marc-hb commented
Interestingly, this makes a lot of tests fail. All of them seem to be because of:
`Initramfs unpacking failed: Decoding failed` or ` EXT4-fs (mmcblk0p2): re-mounted. Opts: errors=remount-ro` or both. Will investigate.

2020-09-09 02:57 UTC, xiulipan commented
@marc-hb I check the CI result. The logs are from very beginning this boot. It should be filter out by our last_line cmd. I think your PR here may have something wrong.
```
 Sep  8 23:32:35 sh-bdw-wsb-rt286-02 kernel: [    0.425729] acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM
Sep  8 23:32:35 sh-bdw-wsb-rt286-02 kernel: [    0.704764] Initramfs unpacking failed: Decoding failed
Sep  8 23:32:35 sh-bdw-wsb-rt286-02 kernel: [    3.368895] EXT4-fs (sda2): re-mounted. Opts: errors=remount-ro
```

2020-09-09 03:05 UTC, xiulipan requested changes

2020-09-09 03:05 UTC, xiulipan commented on tools/sof-kernel-log-check.sh
> +begin_line=$((last_line+1))
Please be aware the if input is 0, we will have fallback.

```
# confirm begin_line is number, if it is not the number, direct using dmesg
[[ "${begin_line//[0-9]/}" ]] && begin_line=0
[[ "$begin_line" -eq 0 ]] && cmd="dmesg" || cmd="sed -n '$begin_line,\$p' /var/log/kern.log"
```

2020-10-24 04:28 UTC, marc-hb commented
Will hopefully be made useless #470. Holding my breath.

2020-12-01 01:02 UTC, marc-hb commented
Made obsolete by #509

2020-12-01 01:29 UTC, closed without merging