sof-kernel-log-check: ignore i2c error for DELL CML HDA laptop
thesofproject/sof-test pull request #425
Opened 2020-10-10 07:25 UTC by RuiqingX

Fixes: #396

Signed-off-by: RuiqingX <ruiqingx.zhang@intel.com>

2020-10-10 22:00 UTC, marc-hb requested changes
Please move these to a platform specific section below:
```
case "$platform" in
```

2020-10-10 22:00 UTC, marc-hb commented on tools/sof-kernel-log-check.sh
> +ignore_str="$ignore_str"'|i915 0000:00:02\.0: \[drm\] ERROR TC cold block failed'
I have a couple questions about the Type-C errors, please check bug 374

2020-10-13 17:34 UTC, marc-hb approved these changes
In the future it would be better to guard more of these with `case $platform`, especially the ones with strings like "DELL0955" in the error message but Rome wasn't built in a day.

2020-10-14 01:33 UTC, RuiqingX commented
fixes and closed.

2020-10-14 02:20 UTC, RuiqingX commented
It was closed by mistake

2020-10-14 04:55 UTC, merged