sof-kernel-log-check.sh: change sed -n $begin,\$p to tail -n +$begin
thesofproject/sof-test pull request #435
Opened 2020-10-14 06:14 UTC by marc-hb

This allows removing "eval" and some quoting headaches.

Also fix the last shellcheck warnings

2020-10-15 08:00 UTC, xiulipan requested changes
I think `declare -p` will output some debug logs. You can keep it as comment out to help developer to debug later but I do not think we should enable it by default.

```
2020-10-14 06:19:16 UTC [REMOTE_INFO] Check sof debug fs environment
2020-10-14 06:19:16 UTC [REMOTE_INFO] Checking ipc flood test!
2020-10-14 06:19:16 UTC [REMOTE_INFO] ===== [1/1] loop Begin =====
2020-10-14 06:19:16 UTC [REMOTE_COMMAND] sudo bash -c 'echo 10000 > /sys/kernel/debug/sof/ipc_flood_count'
declare -- cmd="dmesg"
2020-10-14 06:19:17 UTC [REMOTE_INFO] Dumping test logs!
[  101.921335] sof-audio-pci 0000:00:1f.3: IPC Flood count: 10000, Avg response time: 53016ns
[  101.921335] sof-audio-pci 0000:00:1f.3: Max response time: 123315ns
[  101.921336] sof-audio-pci 0000:00:1f.3: Min response time: 36133ns
declare -- cmd="tail -n  +1283  /var/log/kern.log"
2020-10-14 06:19:17 UTC [REMOTE_INFO] Test Result: PASS!
```

2020-10-15 08:38 UTC, marc-hb commented on tools/sof-kernel-log-check.sh
> +declare -p cmd
No, just useful logging.

2020-10-15 08:42 UTC, marc-hb commented on tools/sof-kernel-log-check.sh
> +declare -p cmd
This log just one line and for now this code is a complicated mess. In commit 8b1092e7b46f you added many more lines to debug an issue in the same area.

2020-10-16 01:44 UTC, marc-hb commented on tools/sof-kernel-log-check.sh
> +declare -p cmd
I commented it out because I care about all the rest much more.

2020-10-16 07:36 UTC, xiulipan approved these changes
@marc-hb Thanks for the clean up. I think the debug log would be useful when we find issues. We should not enable it by default.

2020-10-16 07:36 UTC, merged

2020-10-16 16:09 UTC, marc-hb commented
>  I think the debug log would be useful when we find issues. We should not enable it by default.

I agree except we have _already_ found issues! see #366, your commit 8b1092e7b4, https://github.com/thesofproject/sof-test/pull/354#discussion_r482769591 and probably others