env-check.sh: rewrite complicated and duplicated group membership
thesofproject/sof-test pull request #454
Opened 2020-10-20 19:58 UTC by marc-hb

Simplify and remove duplication, use an array and for loop instead. 450
fewer characters.
Stop parsing files directly, switch to getent system interface instead.
Stop recommending editing file directly, recommend usermod system
interface instead.

Fix the last shellcheck warnings in this file:

In env-check.sh line 107:
```
[[ "$user" ]] && [[ ! $(awk -F ':' '/^adm:/ {print $NF;}' /etc/group|grep "$user") ]] && \
                      ^-- SC2143: Use grep -q instead of comparing output with [ -n .. ].
```
(3 times because of code duplication)

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2020-10-20 20:16 UTC, marc-hb commented
The last shellcheck warnings in this file are fixed in (unrelated) PR #452

2020-10-21 10:28 UTC, xiulipan requested changes
Nice idea but I think it would be better with some function wrapper.

2020-10-21 10:28 UTC, xiulipan commented on env-check.sh
> +for grp in "${!grp_error[@]}"; do
why not wrap this as a function.

```
check_group adm 'Missing permission to access /var/log/kern.log'
check_group sudo 'Missing permission to run command as sudo'
check_group audio 'Missing audio group membership to access /dev/snd/* devices' ```

2020-10-22 02:14 UTC, marc-hb commented on env-check.sh
> +for grp in "${!grp_error[@]}"; do
Good idea, thanks! Done.

2020-10-22 07:29 UTC, xiulipan approved these changes
LGTM

2020-10-22 07:29 UTC, merged