test-case: fix function argument degrading
thesofproject/sof-test pull request #475
Opened 2020-10-27 06:42 UTC by aiChaoSONG

If a shell function takes a variable as its argument,
and the variable is empty, then the argument will
degrade to nothing in the function.

This patch adds quotes to function arguments to avoid
argument degrading.

No functional change, only add quotes.

Signed-off-by: Amery Song <chao.song@intel.com>

2020-10-27 18:47 UTC, marc-hb requested changes
Totally agree with the change except it is way too big. For instance is possible some function calls rely sometimes on white space inside the argument, which is bad (it should use a bash array instead) but working and this would break it.

Please resubmit with only the changes you need right now and with a separate commit per function.

2020-10-28 02:15 UTC, aiChaoSONG commented
@marc-hb Updated, I only need the change for `func_pipeine_export`

2020-10-28 05:10 UTC, xiulipan submitted a review, later dismissed

2020-10-28 17:01 UTC, marc-hb commented
Looks good except you kept the older and now misleading commit subject.

2020-10-29 02:12 UTC, aiChaoSONG commented
@xiulipan Please help to approve this PR again, as I change the misleading commit subject as Marc suggested. Once this get merged, I will test https://github.com/thesofproject/sof-test/pull/430, if the result is good, it can be merged too.

2020-10-29 05:24 UTC, marc-hb requested changes
>  No functional change, only add quotes.

It is a big functional change when the `$tplg` argument is empty or not defined.

2020-10-29 05:24 UTC, marc-hb submitted a review, later dismissed

2020-10-29 16:20 UTC, marc-hb commented
Travis builds delayed everywhere because of the required migration to travis.com https://travis-ci.community/t/builds-hang-in-queued-state/10250  shellcheck would not have been very helpful in this PR because of the number of files changed. I reviewed every line carefully.

The only failure in https://sof-ci.01.org/softestpr/PR475/build346/devicetest/ is a RTC wakeup failure on just one system, this can't be related.

Merging this to unblock #430

2020-10-29 16:22 UTC, marc-hb approved these changes

2020-10-29 16:22 UTC, merged