sof-kernel-log-check:ignore i915 false failure(update)
thesofproject/sof-test pull request #496
Opened 2020-11-06 01:11 UTC by RuiqingX

Fixes: #374

Signed-off-by: RuiqingX <ruiqingx.zhang@intel.com>

2020-11-06 01:39 UTC, aiChaoSONG commented
I don't fully get the point here, why add a pair of raw `*`, could you please explain a little bit?

2020-11-06 05:35 UTC, marc-hb commented
Use `fake_kern_error()` in `case-lib/lib.sh` to locally test `ignore_str` regular expressions  when the real error is intermittent.

2020-11-06 06:13 UTC, xiulipan requested changes
Please add more commit message, a simple fix could not tell anything. Also the commit message should be something start with fix.

2020-11-06 06:13 UTC, xiulipan commented on tools/sof-kernel-log-check.sh
>  # BugLink: https://github.com/thesofproject/sof-test/issues/374
please also put origin error logs here. A link it not enough

2020-11-14 05:41 UTC, marc-hb commented
The code change is good. The commit message says basically nothing. 

Besides an English description of the change it should also contain "Fixes: 589920e6ee83"

2020-11-19 04:19 UTC, aiChaoSONG approved these changes
LGTM

2020-11-19 04:20 UTC, merged