add debug info in multiple-pipeline-playback/capture to root cause #472
thesofproject/sof-test pull request #516
Opened 2020-11-16 09:09 UTC by aiChaoSONG

2020-11-16 23:32 UTC, marc-hb requested changes
Please help review #497 (and others) first.

Also let's not add too much to the already ridiculous amount of copy/paste across these two files (they seem 90% identical!!!). You wrote a function so it should be re-usable without copy/paste/diverge...

2020-11-16 23:34 UTC, marc-hb requested changes
Sorry I just realized you are reducing copy/paste/diverge a bit: from 4 instances to 2 instances. How about finishing the job and going to just one instance?

2020-11-18 04:21 UTC, xiulipan commented
@aiChaoSONG Ping for update, also rebase is needed.

2020-11-18 06:08 UTC, aiChaoSONG commented
@xiulipan @marc-hb Updated, I going to merge the multiple-pipeline-playback.sh and multiple-pipeline-capture.sh into one script later, so some common code is still there. the function func_error_exit can be used by other scripts later,so it is moved to lib.sh

2020-11-18 06:34 UTC, xiulipan requested changes
try to use local in loops or functions to avoid wrong usage.

2020-11-18 06:34 UTC, xiulipan commented on test-case/multiple-pipeline-playback.sh
> +    tmp_count=$max_count
use local for the tmp_count if you do not want it to be used outside.

2020-11-18 06:34 UTC, xiulipan commented on test-case/multiple-pipeline-playback.sh
> +    [[ $overall_count -eq $max_count ]] ||
use `local` for the `overall_count`

2020-11-18 06:55 UTC, marc-hb commented
> Please help review #497 (and others) first.

I screwed up #497, apologies. Tentative (and urgent) fix in #521. 

It's not practical to work on the same code at the same time because it will cause git conflicts. @aiChaoSONG please pause your work on the multiple pipelines tests for a couple days until I'm done with:
- urgent fix #521 
- waiting a day or two to make sure I didn't screw up even more
- re-synchronizing multiple-pipeline-playback with multiple-pipeline-capture (I totally missed the massive copy/paste)

Once I'm all done I promise these tests will be all yours to deduplicate and clean-up! Appreciated.

2020-11-18 23:33 UTC, marc-hb commented
> re-synchronizing multiple-pipeline-playback with multiple-pipeline-capture (I totally missed the massive copy/paste)

Submitted in #525

2020-12-01 01:38 UTC, marc-hb commented
I think I got the root cause, see candidate fix in #538

2021-01-14 03:10 UTC, aiChaoSONG commented
@472 is already root caused and fixed, close.

2021-01-14 03:10 UTC, closed without merging