sof-kernel-log-check: fix to filter out USB3.1 suspend/resume error
thesofproject/sof-test pull request #549
Opened 2020-12-08 02:27 UTC by fredoh9

'.' is single charactor. Template string doesn't need error number
to have.

Signed-off-by: Fred Oh <fred.oh@linux.intel.com>

2020-12-08 02:37 UTC, aiChaoSONG reviewed
@fredoh9 Let have a quick fix and merge

2020-12-08 02:37 UTC, aiChaoSONG commented on tools/sof-kernel-log-check.sh
> +ignore_str="$ignore_str"'|usb 3-..: device descriptor read/64, error'
I don't think this is going to work well,  the `usb 3-..` is not going to work if we have `usb 3-4`, and we have!!!
This is better:
```
ignore_str="$ignore_str"'|usb 3-.+: device descriptor read/64, error .+'
ignore_str="$ignore_str"'|usb 3-.+: device not accepting address .+, error .+'
```

there is one more usb error in report 1021
```
[ 6688.142149] kernel: usb usb3-port10: unable to enumerate USB device
```
add an re like this
```
usb usb.-port.+: unable to enumerate USB device
```

2020-12-08 02:38 UTC, aiChaoSONG commented on tools/sof-kernel-log-check.sh
> +ignore_str="$ignore_str"'|usb 3-..: device descriptor read/64, error'
all above re are tested locally.

2020-12-08 04:05 UTC, marc-hb requested changes
The trailing `.+` is misleading because AFAIK we don't perform full line matching, can you please use `fake_kern_error` and re-test without it?

It still works but generates the confusion that we perform full line matching and will be copied by future users.

2020-12-08 04:09 UTC, aiChaoSONG commented
@marc-hb I have tested old RE with a single dot, confirmed not work.

2020-12-08 05:39 UTC, aiChaoSONG approved these changes

2020-12-08 05:40 UTC, merged

2020-12-08 19:57 UTC, marc-hb commented
@aiChaoSONG 

> The TRAILING (last) `.+` is misleading 

If the TRAILING `.+` was required, many of the other filters wouldn't work.

@fredoh9 can you test and submit a fixup removing the trailing `.+`?

2021-03-06 15:48 UTC, marc-hb commented
I think the `.+.` in the middle was a but, fixed in #624