sof-kernel-log-check: ignore net related error
thesofproject/sof-test pull request #566
Opened 2020-12-29 08:14 UTC by xiulipan

add ignore for asix and e1000e seriers network adapter

Signed-off-by: Pan Xiuli <xiuli.pan@linux.intel.com>

Fix #564 #565

2021-01-04 07:38 UTC, keqiaozhang approved these changes

2021-01-04 07:52 UTC, aiChaoSONG requested changes

2021-01-04 07:52 UTC, aiChaoSONG commented on tools/sof-kernel-log-check.sh
> +ignore_str="$ignore_str"'|e1000e .*:'
`*`: match zero or more characters
`.`: match exactly one character
`.+`: match one or more characters
if you want to ignore all asix and e1000e error messages, below is enough, means any error messages contains asix or e1000e will be ignored.
```
ignore_str="$ignore_str"'|asix'
ignore_str="$ignore_str"'|e1000e'
```

2021-01-04 18:10 UTC, marc-hb requested changes
I don't think we can ignore ALL network errors unconditionally because we depend on the network for everything. Especially not now that we filter with error levels thanks to `journalctl`, which means all errors are actual, severe errors and not just warning or info messages with "error" in the name.

What specific errors were observed?

2021-01-05 00:49 UTC, keqiaozhang commented
> I don't think we can ignore ALL network errors unconditionally because we depend on the network for everything. Especially not now that we filter with error levels thanks to `journalctl`, which means all errors are actual, severe errors and not just warning or info messages with "error" in the name.
> 
> What specific errors were observed?

We have 2 kinds of net errors:https://github.com/thesofproject/sof-test/issues/565 and https://github.com/thesofproject/sof-test/issues/564.  
I assigned the first one to myself and trying to fix it now.

2021-01-05 02:31 UTC, closed without merging

2021-01-05 02:33 UTC, xiulipan commented
close as we need to discuss if we would ignore the net related error.