sof-kernel-log-check: ignore ACPI _ADR workaround
thesofproject/sof-test pull request #590
Opened 2021-01-22 20:27 UTC by plbossart

PR https://github.com/thesofproject/linux/pull/2701 introduces a
workaround which leads to errors being thrown when the DSDT contains a
device with the 0x701 part_id.

Ignore the error since it's a normal error flow.

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>

2021-01-22 20:42 UTC, plbossart commented
@marc-hb GitActions issue here unrelated to this PR?

2021-01-24 02:31 UTC, marc-hb requested changes
> @marc-hb GitActions issue here unrelated to this PR?

Pylint failure is indeed unrelated; you didn't submit any Python. The Github Ubuntu VM is out of date, see #588 hack if you're interested (you're not)

2021-01-24 02:31 UTC, marc-hb commented on tools/sof-kernel-log-check.sh
> +
Can you guard this with:
```shell
if [ "$platform" = xxx ] ; then
  ignore_str="$ignore_str"'|rt711 ...'
  ignore_str="$ignore_str"'|rt1308 ...'
fi 
```
The PR URL is super useful but... very long! Can you also add just a couple words like:
```shell
# some BIOSes are  buggy so we need to probe like mad.
```
This helps a lot with future maintenance of this file.

2021-02-03 15:39 UTC, plbossart commented
no longer needed, we chose a different implementation in the Linux kernel.

2021-02-03 15:39 UTC, closed without merging