check-sof-logger: rewrite most of it so it can actually find bugs
thesofproject/sof-test pull request #666
Opened 2021-04-27 04:38 UTC by marc-hb

Probably the main change is fixing the huge etrace test gaps #321 and
https://github.com/thesofproject/sof/issues/3281

Also fixes DMA trace gaps #297 and #298

I initial tried to preserve some of the existing code but it was just
too bad. PR #161 / commit 7274f490b78 seemed especially bad:

- It tried to ignore a specific `ll drift` error but instead it filtered
out almost every log statement out of... stderr, that does not have show
log statements!! (Just for the record this `ll drift` error has been
downgraded to warning now, see
https://github.com/thesofproject/sof/pull/2686 and
https://github.com/thesofproject/sof/issues/3854)

- That same commit also added code that merely starts the DMA trace with
"there is an error below" (without failing the test) but that's eclipsed
by the entire log that follows. Later, the firmware started printing
ERROR every single time when the ERROR FW ABI prefix was introduced yet
no one ever noticed which proves how useless this prefix is was.

So remove this DMA trace prefix as the purpose of this test is - as
clearly stated in #167 - not to find firmware errors but errors with the
sof-logger itself (even though we never had anything looking at firmware
errors so far)

Don't grep for "error" on stderr: anything on stderr is a logger
failure (not a firmware failure).

Don't require whitespace before the TIMESTAMP header.

Add set -e.

Use shell functions.

Signed-off-by: Marc Herbert <marc.herbert@intel.com>

2021-04-27 05:26 UTC, marc-hb commented
https://sof-ci.01.org/softestpr/PR666/build677/devicetest is all green!

2021-04-27 05:31 UTC, marc-hb commented
@aiChaoSONG , @fredoh9 these "Log $ftype BEG>>" changes seem to break some CI parsing, see for instance the bottom of https://sof-ci.01.org/softestpr/PR666/build677/devicetest/?model=CML_RVP_SDW&testcase=check-sof-logger

Any idea what exactly breaks and maybe how?

2021-04-27 05:37 UTC, aiChaoSONG commented
@marc-hb drivers.audio.ci.sof-jenkins/blob/main/json2html.py this file will add some style to plain text log, and transform log into html format, in html format, pair of `<any contents>` can not display.

2021-04-27 05:38 UTC, marc-hb commented
Thanks for the pointer! BTW how come these tests pass without any TIMEOUT? They don't print PASS at the end! The similar situation in #661 caused TIMEOUTs

2021-04-27 05:41 UTC, aiChaoSONG commented
@marc-hb No, there is!!!, if you check the source from your browser, it looks like this:

![image](https://user-images.githubusercontent.com/52959957/116191061-42897080-a75e-11eb-9793-89a023f7000d.png)

2021-04-27 05:46 UTC, marc-hb commented
Got it, thanks! Looks like I just invented the invisible PASS :-)

2021-04-27 22:22 UTC, marc-hb commented
@aiChaoSONG , @fredoh9 , @keqiaozhang : I thought this PR just broke some code looking for `Log data BEG>>` and `<<END whatever` but actually:

- I found nothing looking for `BEG` in the repo @aiChaoSONG  pointed at,
- This has been broken long before this PR, see `check-sof-logger` results in for instance older https://sof-ci.01.org/sofpr/PR3995/build8564/devicetest/?model=CML_HEL_RT5682&testcase=check-sof-logger

2021-04-28 00:50 UTC, marc-hb commented
https://sof-ci.01.org/softestpr/PR666/build680/devicetest/?model=APL_UP2_NOCODEC&testcase=check-suspend-resume-with-playback is the usual #650 TIMEOUT, everything else is green.

In the same run the check-sof-logger outputs look OK except the 2, now 4 `logger` tabs are all empty but that's a problem that long predates this PR (example at https://sof-ci.01.org/sofpr/PR3995/build8564/devicetest/?model=CML_HEL_RT5682&testcase=check-sof-logger )

Long story short this PR is ready however I'd like much smaller PR #668 to go first to be cautious and make really really sure the `BEG>>` -> `BEG::` change does not break anything. Maybe the reason it does not break anything is because it's already broken?

2021-04-28 05:57 UTC, marc-hb commented
https://sof-ci.01.org/softestpr/PR666/build681/devicetest has the usual #650 TIMEOUT and everything else is green and looks good.

The `dmesg` and `logger` tabs are empty for this test (and for this test only) but that's not new at all.

2021-05-26 05:27 UTC, marc-hb commented
SOFCI TEST

2021-05-26 07:21 UTC, aiChaoSONG commented
Seems this case generated several logger log files.
![image](https://user-images.githubusercontent.com/52959957/119618822-e89bc980-be35-11eb-8998-8393b4d38501.png)

2021-05-26 18:03 UTC, marc-hb commented
> Seems this case generated several empty logger log files.

Yes this is known, UI issue, see comments and links above. It's not caused by this PR. You can still download the logs, only the UI is empty.

The only difference this PR makes is that there are now 4 empty tabs instead of 2.

2021-06-07 06:59 UTC, aiChaoSONG requested changes
Once the log file are renamed to *.txt, it is good to merge. thank you @marc-hb

2021-06-07 06:59 UTC, aiChaoSONG commented on test-case/check-sof-logger.sh
> +        local tracef="$LOG_ROOT/logger.$f.log"
ditto

2021-06-07 06:59 UTC, aiChaoSONG commented on test-case/check-sof-logger.sh
> +        local stderr_file="$LOG_ROOT/logger.$f.log"
ditto

2021-06-07 06:59 UTC, aiChaoSONG commented on test-case/check-sof-logger.sh
> +        bname="logger.$ftype.log"
ditto

2021-06-07 06:59 UTC, aiChaoSONG commented on test-case/check-sof-logger.sh
> +etrace_stderr_file=$LOG_ROOT/logger.etrace_stderr.log
ditto.

2021-06-07 06:59 UTC, aiChaoSONG commented on test-case/check-sof-logger.sh
>  error_file=$LOG_ROOT/logger.error.log
The web cannot render .log file, so it automatically download it for you, that's what you see in the internal web, please rename it to *.txt.

2021-06-09 18:37 UTC, marc-hb commented
The `[ 1034.664354] kernel: IO error in rt700_jack_detect_handler, ret -16` in https://sof-ci.01.org/softestpr/PR666/build721/devicetest/?model=CML_RVP_SDW&testcase=check-suspend-resume-5 is the well known  https://github.com/thesofproject/linux/issues/2943

In the same run, the logger tabs are visible and not auto-downloaded like the .log files were. Thanks @aiChaoSONG ! It's still confusing to have all 4 of them named the same and to have the stderr tabs empty but that can be fixed later.

2021-06-10 01:54 UTC, aiChaoSONG approved these changes

2021-06-10 04:11 UTC, marc-hb commented
Thanks @aiChaoSONG . This had been in review for months and  badly needed for tracing changes like thesofproject/sof#4327 and others. Merging.

2021-06-10 04:11 UTC, merged