multiple-pipeline: add delay before ps_checks
thesofproject/sof-test pull request #674
Opened 2021-05-05 04:02 UTC by fredoh9

Sometimes last aplay or arecord process might delay to start. This causes
the test case to fail due to number of PIDs mistmatch. This is not 100%
reproducible but slower platform has more chance to fail.

Signed-off-by: Fred Oh <fred.oh@linux.intel.com>

2021-05-05 04:30 UTC, marc-hb requested changes
I think we unfortunately need this because of my tentative explanation in #672. If you agree with it then please summarize it in the comment here and maybe add a link to it.

2021-05-05 04:44 UTC, fredoh9 commented
@marc-hb left a detailed explanation about the problem. We will find better management of background processes... later.
https://github.com/thesofproject/sof-test/issues/672#issuecomment-832403391

2021-05-08 05:04 UTC, aiChaoSONG commented
@keqiaozhang @fredoh9 @marc-hb  As I observed from Keqiao's demo, aplay/arecord process from last iteration may not be fully killed at the current iteration, so are you sure it is due to `delay to start`, rather than `not fully killed`?

2021-05-08 06:00 UTC, marc-hb commented
BTW I would like to close this PR, superseded by PR #676. So can we keep the discussion in bug #672?

2021-05-08 06:14 UTC, aiChaoSONG commented
> Which demo? "Not fully killed" sounds like another issue.

When Keqiao found the issue days before, he ran this case once, and I checked the log.

Without the sleep here, for example, in iteration 0, four aplay/arecord processes are started and killed, PIDs = [0 1 2 3], In the second iteration, we start four aplay/arecord again, PIDs=[4 5 6 7], but in the first ps check of the second iteration, six aplay/arecord processes are detected, PIDs=[0 1 4 5 6 7], two are from iteration 0, in the second ps check of the second iteration, only four pipelines are detected(PIDs=[ 4 5 6 7]), and test case thinks it started 6 process, but only 4 were alive at the end, so it failed.

That's why I said `not fully killed`, resources are released (we can run aplay on the same pcm), but process not fully cleaned.  Hope I have made me clear to you.

2021-05-10 13:44 UTC, fredoh9 commented
https://github.com/thesofproject/sof-test/pull/676 is merged

2021-05-10 13:44 UTC, closed without merging

2021-05-10 16:16 UTC, marc-hb commented
Thanks @aiChaoSONG , that really sounds like a different issue to me. Let's keep an eye on it and if it happens again let's please discuss it in a better place  than in this abandoned PR :-)

2021-05-11 13:48 UTC, fredoh9 commented
@marc-hb @keqiaozhang @aiChaoSONG Yes that is different issue. If you have seen that problem, please open a new issue. I remember the same error in long time agon. I think that will be not so easy to reproduce the problem.