sof-kernel-log-check: unify error filters for mei_me module
thesofproject/sof-test pull request #881
Opened 2022-03-18 02:32 UTC by keqiaozhang

CI detected various of mei_me errors on different platforms
specific mei_me error filters cannot cover so many variants
This patch unifys the filters to skip all of them.

Signed-off-by: Keqiao Zhang <keqiao.zhang@intel.com>

2022-03-18 03:24 UTC, marc-hb requested changes
At the very least we shouldn't lose the comments with the list of known error messages and platforms known failing.

Has there been a recent surge of ME error messages?  If yes we must at least keep track of when it happened, that's part of our open source community excellence mandate.

On which platforms? Are these new error messages? The commit message does not say anything.

Also, ignoring ME error messages is very risky considering we depend totally on the ME for booting.

2022-06-07 00:03 UTC, marc-hb commented
From internal discussion 246:

> WHL at least on 12.0.92.XXXX, so anything lower will not be supported

So we could ignore all errors from this driver when `/sys/class/mei/mei0/fw_ver` is lower on WHL.

But @keqiaozhang I have not seen any unignored `mei_me` error recently have you?

2022-06-07 00:40 UTC, keqiaozhang commented
> 
> But @keqiaozhang I have not seen any unignored `mei_me` error recently have you?

The last time I saw the `mei_me` error was about 2 weeks ago:
![image](https://user-images.githubusercontent.com/22468760/172271713-8dfde61f-8664-4eae-ae83-5964a3d6bb82.png)

2022-06-13 01:11 UTC, keqiaozhang commented
Observed this issue on TGLH_SKU0A70_HDA
http://sof-ci.sh.intel.com/#/result/planresultdetail/13257?model=TGLH_SKU0A70_HDA&testcase=check-suspend-resume-50:
```
[ 8120.420547] kernel: asix 3-3.1:1.0 enx000ec6798782: Link is Down
[ 8121.813446] kernel: mei_me 0000:00:16.0: wait hw ready failed
[ 8121.813450] kernel: mei_me 0000:00:16.0: hw_start failed ret = -62
[ 8121.813610] kernel: mei_me 0000:00:16.0: unexpected reset: dev_state = RESETTING fw status = 90000255 39850106 00000020 00004000 00000000 03C00000
```

2022-09-21 07:16 UTC, keqiaozhang commented
@marc-hb  can we merge this PR? As the `mei_me` issue continues to happen on WHL-UP board and Dell-SKU0A70.
According to https://github.com/intel-innersource/drivers.audio.ci.sof-framework/issues/246, we are unlikely to fix the issue.

2022-09-21 08:02 UTC, plbossart approved these changes
Agree, we don't care about mei_me, this is not useful/relevant for our work.

2022-09-21 22:26 UTC, marc-hb commented
> At the very least we shouldn't lose the comments with the list of known error messages and platforms known failing.

Ping?

"unify" != "delete useful pointers and information"

2022-09-22 06:05 UTC, keqiaozhang commented
> "unify" != "delete useful pointers and information"

Keep existing information and pointers and added new.

2022-09-22 06:20 UTC, marc-hb approved these changes

2022-09-22 06:46 UTC, merged

2022-09-22 19:05 UTC, greg-intel reviewed
Glad to see this merged.