[RFC]: Add initial patches for sof-test i.MX support
thesofproject/sof-test pull request #926
Opened 2022-07-07 12:10 UTC by LaurentiuM1234

We want to use sof-test in our setup which is based on YOCTO distro. Please let us know if you think sof-test can be multiplatform.

2022-07-07 15:00 UTC, plbossart reviewed
It'd be fantastic if sof-test is run on multiple platforms, thanks @LaurentiuM1234

2022-07-07 15:00 UTC, plbossart commented on case-lib/lib.sh
> +    rm $WRITE_SPEED_CHECK_DUMMY_FILE
Also not sure why this write check was added unconditionally, it was meant to debug some issues with mass storage but I don't think it needs to be a key feature that is run in all cases on all platforms, it should be opt-in. @marc-hb this is likely for you to comment on.

2022-07-07 17:52 UTC, marc-hb requested changes
We should absolutely make the code able to run without git but not like this.

2022-07-11 12:09 UTC, dbaluta commented
@LaurentiuM1234 @plbossart thanks for comments. We will go with your suggestions and update this PR.

2022-07-11 13:15 UTC, LaurentiuM1234 commented
Thanks for all the comments @marc-hb @plbossart ! Following your suggestions, I have made the following adjustments:
1) The `git log` command is now piped to the `true` command so as to allow the tests to run on platforms which don't have the `git` command. This modification avoids all the extra code you have pointed out.
2) The storage checks are now done based on the value of the SKIP_STORAGE_CHECKS env variable. Based on this: 

> We're current replacing the drives and should turn this off soon.
> If you can't wait and really need to turn this off right now then add a conditional around the only place where storage_checks is invoked. It's quite strange to keep running a test that write from /dev/zero to /dev/null and prints some pointless logs.

I have decided to use an env variable as a temporary solution that will allow the tests to run on i.MX until the storage checks are turned off.

2022-07-11 20:42 UTC, marc-hb requested changes
Almost there

2022-07-11 20:42 UTC, marc-hb commented on case-lib/opt.sh
> +            git -C "$SCRIPT_HOME" log --oneline --decorate -n 5 | true
```suggestion
            git -C "$SCRIPT_HOME" log --oneline --decorate -n 5 || true
```
I'm sorry my earlier typo mislead you.

Compare:
```shell
printf foo | true
printf foo || true
```

2022-07-11 21:56 UTC, marc-hb requested changes

2022-07-11 21:56 UTC, marc-hb commented on case-lib/hijack.sh
> +    if [ ! "$SKIP_STORAGE_CHECKS" -eq 1 ]; then
Nit
```suggestion
    [ "$SKIP_STORAGE_CHECKS" -eq 1 ] || storage_checks ||
        exit_status=1
```
The fewer negations the better and `!` can't be copied to the command-line.

2022-07-11 21:56 UTC, marc-hb approved these changes

2022-07-12 00:50 UTC, marc-hb commented on case-lib/config.sh
> +SKIP_STORAGE_CHECKS=${SKIP_STORAGE_CHECKS:-0}
Change of mind sorry, can you please remove the negation and make this `ENABLE_STORAGE_CHECKS, defaulting to 1`? Later we can just change the default to zero.

2022-07-12 00:50 UTC, marc-hb commented on case-lib/hijack.sh
> +    if [ ! "$SKIP_STORAGE_CHECKS" -eq 1 ]; then
Change of mind sorry
```shell
if [ "$ENABLE_STORAGE_CHECKS" = '1' ]; then
   storage_checks || exit_status=1
fi
```
Zero negation; no need.

2022-07-12 08:22 UTC, LaurentiuM1234 commented
Thanks again for the suggestions @marc-hb !

1) Regarding the git command: this was a slip on my behalf. I should have ran `shellscript` locally and this could probably have been avoided.
2) Regarding the storage checks: I agree the negation was not necessary. Now the code should be much more clear.

2022-07-12 11:37 UTC, dbaluta approved these changes

2022-07-12 14:55 UTC, marc-hb approved these changes
This one is small and has been in review for 5 days - merging.

2022-07-12 14:55 UTC, merged