[RFC]: Pipe journalctl command to grep instead of using the -g option
thesofproject/sof-test pull request #934
Opened 2022-07-14 12:26 UTC by LaurentiuM1234

The reason for this is to allow the tests based on journalctl -g "some string" to run on i.MX platforms. At this moment, running
journalctl -q -k -g "loading" results in the following error: Compiled without pattern matching support.

2022-07-14 17:21 UTC, marc-hb requested changes
`--grep` is case insensitive so to be equivalent this should be `grep -i`

Note piping is MUCH slower. Impact should hopefully be OK because we only search the current boot.

2022-07-14 17:46 UTC, fredoh9 commented
I don't understand why current -g option is not working in i.MX platforms? Can you elaborate more?

2022-07-14 18:00 UTC, marc-hb commented
@fredoh9 some journalctl features can be removed at compile time to save space.

BTW @LaurentiuM1234 the commit message is incorrect; this problem is related to your particular Yocto configuration, it's not related to i.MXX

2022-07-15 10:11 UTC, paulstelian97 commented
Um, we shouldn't have merge commits inside a pull request, at least in SOF firmware/test projects. Can a rebase be done so that the merge commit is unneeded?

2022-07-15 10:48 UTC, LaurentiuM1234 commented
@paulstelian97 Yeah, sorry about that. Will start marking the PRs as drafts in case more mistakes like that happen again.
@marc-hb Thanks for pointing out the mistakes. Now the grep command is called with the -i command and the commit messages should be correct.

2022-07-15 23:56 UTC, marc-hb approved these changes

2022-07-17 04:11 UTC, marc-hb commented
I always start all my PRs as draft, it's a good habit.

2022-07-17 04:11 UTC, merged