check-sof-logger: add support for mtrace log with IPC4
thesofproject/sof-test pull request #971
Opened 2022-10-14 14:59 UTC by kv2019i

Add support for "mtrace" debugfs interface implemented by SOF driver when it is used in IPC4 mode. Use this instead of cavstool.py.

BugLink: https://github.com/thesofproject/sof-test/issues/970
Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>

2022-10-14 15:44 UTC, kv2019i commented
Hmm, something wrong still. Locally this works, but in CI run, logger output file is empty:
```
2022-10-14 15:17:24 UTC [REMOTE_ERROR] Log header not found in /home/ubuntu/sof-test/logs/check-sof-logger/2022-10-14-15:17:14-27972/logger.etrace.txt
```

The file seems to be completely empty, so need to debug more before marking as non-draft.

2022-10-17 09:20 UTC, kv2019i commented
V2 update:
 - ready for review, added comments and updated documentation
 - this is only cause for repeated failures in current PR test, see e.g. https://github.com/thesofproject/sof/pull/6383

2022-10-17 18:10 UTC, marc-hb requested changes
Thanks @kv2019i for the huge effort updating this awkward and I assume unfamiliar code.

Mostly OK, my main concern are complexity and readability which were already bad and made even more difficult by this. For now "section headers" should be enough, see suggestion below. Also missing a straight-forward update in lib.sh.

2022-10-17 18:10 UTC, marc-hb commented on test-case/check-sof-logger.sh
> +    if ! is_ipc4 ; then
```suggestion
    # legacy sof-logger shared SRAM collection for XTOS 
    if ! is_ipc4 ; then
```

2022-10-17 18:10 UTC, marc-hb commented on test-case/check-sof-logger.sh
> +        else
```suggestion
        # IPC3 Zephyr
        else
```

2022-10-17 18:10 UTC, marc-hb commented on test-case/check-sof-logger.sh
> +            return 0
```suggestion
       # sof-logger was checked above
```

2022-10-17 18:10 UTC, marc-hb commented on test-case/check-sof-logger.sh
> +            # mtrace
```suggestion
      # mtrace has no tool banner. Let's be happy with any log statement
```

2022-10-19 20:52 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +##    Fimrware log output is detected and the tools did not report error
Thanks, added. Needed to check man grep to understand what my patch now does.

2022-10-19 20:55 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +        if sudo test -e ${CARD_NODE} ; then break; fi
Ack, applied to next revision.

2022-10-19 20:56 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +                    return 1
Ack, will fix.

2022-10-19 20:56 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +                 "$mtracetool" > "$etrace_file" 2> "$etrace_stderr_file" & mtracetoolPID=$!
Currently it is, but tool might go significant developments still, so better to check for stderr output as well.

2022-10-19 21:06 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +        if is_ipc4 ; then
I added the section headers to all branches to make this more readable. Refactoring would not hurt, but there's going to be still more changes here (for dictionary support and probes), so code is going to see more churn still as Zephyr logging backend support is being worked on.

2022-10-19 21:07 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +    if ! is_ipc4 ; then
I put more explicit comment on sof-logger. It's a interface specific to IPC3 and not so much related to the OS.

2022-10-19 21:15 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +            return 0
Thanks, this can be done as a common step for all Zephyr backends.

2022-10-19 21:15 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +        else
Ditto here.

2022-10-19 21:17 UTC, kv2019i commented on test-case/check-sof-logger.sh
> +            # mtrace
Done.

2022-10-19 21:25 UTC, kv2019i commented
V3 update:
- addressed comments from @marc-hb (thanks for the extensive review and suggestions)

2022-10-20 00:01 UTC, marc-hb approved these changes
Thanks @kv2019i ! @keqiaozhang, others can someone else give this a second look?

2022-10-20 02:14 UTC, keqiaozhang approved these changes
Local test passed, I'm OK with this PR.

2022-10-20 05:37 UTC, merged