lib: set locale to avoid alsabat failure
thesofproject/sof-test pull request #993
Opened 2022-12-19 09:05 UTC by miRoox

alsabat returns -2 for "C" locale, set standard locale to smooth out the difference between users.

Signed-off-by: Yong-an Lu <yongan.lu@intel.com>

2022-12-19 17:58 UTC, marc-hb requested changes

2022-12-19 17:58 UTC, marc-hb commented on case-lib/lib.sh
> +        return 2
This looks like a git accident.

2022-12-19 17:58 UTC, marc-hb commented on case-lib/lib.sh
> +export LC_ALL=en_US.UTF-8
This change is good but wait: why is alsabat failing with a "C" locale and how? This sounds really bad. Please file a bug if none exists yet.

2022-12-21 05:41 UTC, marc-hb approved these changes

2022-12-21 05:57 UTC, marc-hb requested changes
> alsabat returns -2 for "C" locale,

I tried to reproduce but the test passed:

```shell
export LC_ALL=C
ubuntu@jf-adlp-rvp-nocodec-8:~$ TPLG=/lib/firmware/intel/sof-tplg/sof-adl-nocodec.tplg MODEL=ADLP_RVP_NOCODEC_ZEPHYR ~/sof-test/test-case/check-alsabat.sh -p hw:sofnocodec,0 -c hw:sofnocodec,0 -C 2

PASS

```

We need more information.

2022-12-21 06:12 UTC, marc-hb commented on case-lib/lib.sh
> +export LC_ALL=en_US.UTF-8
> Please file a bug if none exists yet.

We already have https://github.com/intel-innersource/drivers.audio.ci.sof-framework/issues/286 but it is: 1. private 2. incomplete.

2023-02-14 23:04 UTC, greg-intel commented
SOFCI TEST

2023-02-22 10:47 UTC, miRoox commented
The device test error is unrelated.

2023-02-22 20:15 UTC, greg-intel approved these changes

2023-02-23 00:26 UTC, marc-hb requested changes
Thanks @miRoox for filing https://github.com/alsa-project/alsa-utils/issues/192, very useful.

I did some testing and added more information in 192.

Based on my latest discoveries I think hardcoding the locale like this is too strict. Weird and very specific bug 192 aside, `alsabat` does not require any specific locale and neither does ALSA in general. So wee should not block people from testing with different locales. 

How about something like this instead in check-alsabat.sh:

```sh
if locale | grep -i 'C.utf-8'; then
  die 'Try C.utf8 instead, see https://github.com/alsa-project/alsa-utils/issues/192'
fi
```

I'll do it if you don't want to.

2023-02-23 03:14 UTC, marc-hb submitted a review, later dismissed
Did you test this? I didn't.

2023-02-23 05:22 UTC, miRoox commented
> Did you test this? I didn't.

Maybe died too early?

```
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC=C.UTF-8
LC_TIME=C.UTF-8
LC_COLLATE="C.UTF-8"
LC_MONETARY=C.UTF-8
LC_MESSAGES="C.UTF-8"
LC_PAPER=C.UTF-8
LC_NAME=C.UTF-8
LC_ADDRESS=C.UTF-8
LC_TELEPHONE=C.UTF-8
LC_MEASUREMENT=C.UTF-8
LC_IDENTIFICATION=C.UTF-8
/home/ubuntu/sof-test/test-case/../case-lib/lib.sh: line 32: die: command not found
2023-02-23 05:17:55 UTC [ERROR] Starting func_exit_handler(), exit status=127, FUNCNAME stack:
2023-02-23 05:17:55 UTC [ERROR]  source()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2023-02-23 05:17:55 UTC [ERROR]  main()  @  /home/ubuntu/sof-test/test-case/verify-kernel-boot-log.sh:19
/home/ubuntu/sof-test/case-lib/hijack.sh: line 28: is_ipc4: command not found
/home/ubuntu/sof-test/case-lib/hijack.sh: line 104: is_ipc4: command not found
/home/ubuntu/sof-test/case-lib/hijack.sh: line 113: stop_test: command not found
2023-02-23 05:17:55 UTC [ERROR] Kernel check point "KERNEL_CHECKPOINT" is not properly set
2023-02-23 05:17:55 UTC [ERROR] KERNEL_CHECKPOINT=
2023-02-23 05:17:55 UTC [INFO] Test Result: FAIL!
```

2023-02-23 11:42 UTC, miRoox commented
```
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC=C.UTF-8
LC_TIME=C.UTF-8
LC_COLLATE="C.UTF-8"
LC_MONETARY=C.UTF-8
LC_MESSAGES="C.UTF-8"
LC_PAPER=C.UTF-8
LC_NAME=C.UTF-8
LC_ADDRESS=C.UTF-8
LC_TELEPHONE=C.UTF-8
LC_MEASUREMENT=C.UTF-8
LC_IDENTIFICATION=C.UTF-8
2023-02-23 11:40:48 UTC [ERROR] Try C.utf8 instead, see https://github.com/alsa-project/alsa-utils/issues/192
2023-02-23 11:40:48 UTC [ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2023-02-23 11:40:48 UTC [ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
2023-02-23 11:40:48 UTC [ERROR]  check_locale_for_alsabat()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh:790
2023-02-23 11:40:48 UTC [ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-alsabat.sh:61
2023-02-23 11:40:49 UTC [INFO] ktime=15629 sof-test PID=5829: ending
2023-02-23 11:40:49 UTC [INFO] Test Result: FAIL!
```

2023-02-23 19:09 UTC, marc-hb approved these changes

2023-02-23 19:09 UTC, marc-hb commented on test-case/check-fw-echo-reference.sh
> +source "$(dirname "${BASH_SOURCE[0]}")"/../case-lib/lib.sh
I think you could have just moved the shellcheck comment one-line down instead but no big deal.

2023-02-23 19:09 UTC, marc-hb commented
Usual suspend/resume failures in https://sof-ci.01.org/softestpr/PR993/build157/devicetest/index.html, everything else passing.

2023-02-27 06:02 UTC, aiChaoSONG approved these changes

2023-02-27 06:02 UTC, keqiaozhang approved these changes

2023-02-27 06:02 UTC, merged

2023-03-01 01:13 UTC, marc-hb commented
The alsabat bug has just been fixed but let's keep that in place for at least a few months: sof-test should not require all users to upgrade alsa-utils immediately and removing one `-` character in the locale name should be a very small inconvenience.